version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        ports:
            - "8011:8011"
        volumes:
            - ./:/go/src/app
        networks:
            - database-docker_default

networks:
    database-docker_default:
        external: true
